### ISSUE TITLE
安卓底部tab导航可以如何接入

### ISSUE THREAD

**Issue by anicy** [bmfe/WeexErosFramework#14]
请问使用framework的时候，想用原生做底部导航，采用fragment的方式，应该如何与framework中的weex页面渲染结合起来？
如微信下方 微信，联系人，我的 这些导航， 每页则想通过vue的方式进行实现。求教可以如何实现？ 谢谢

**Comment by hanliuxin5** [comment]
请移步 https://github.com/bmfe/eros-template/issues 提出，这里没人来看的。。

然后具体你说的问题，eros 有一个对应解决该问题的标签，到那里问问吧

**Comment by anicy** [comment]
ok thanks
