### ISSUE TITLE
如果可以把项目里的扩展做成weex的plugin的话将是很好的

### ISSUE THREAD

**Issue by nyrf** [bmfe/WeexErosFramework#3]
感谢开源这么个好的项目，现在weex 有个 plugin系统，我发现这个项目里好多功能，如果可以做成weex的plugin的话，应该能为很多人提供很大的帮助，谢谢

**Comment by PerseveranceZ** [comment]
是的，我们下一阶段会接入plugin ，来解决动态加载的问题，至于是用weex官方的还是自定义的，这个还是需要商榷来看成本的。
