### ISSUE TITLE
Eros 开发文档中的一个细节待更新

### ISSUE THREAD

**Issue by hanliuxin5** [bmfe/WeexErosFramework#8]
问题：文档描述不清

位置：https://bmfe.github.io/eros-docs/#/zh-cn/eros_widget?id=axios%ef%bc%88%e8%af%b7%e6%b1%82%ef%bc%89

具体描述：使用该模块方法时提到``` name: 'common.getInfo', //当前是在apis中配置的别名，你也可以直接绝对路径请求 http://xx.xx.com/xxx/xxx```，但是其实如果需要直接使用绝对路径，需要写成```url:'http://www.baidu.com'```

**Comment by aa453509345** [comment]
fixed, Thanks bro !
