### ISSUE TITLE
在使用$router跳转时遇到的报错

### ISSUE THREAD

**Issue by ShineLaw** [bmfe/WeexErosFramework#9]
在homePage中的mounted方法里使用了一个跳转，报错见附件图片
![tim 20180314102832](https://user-images.githubusercontent.com/37200919/37380632-7b8ecaf0-2774-11e8-8003-77d44cbfe4f1.png)

**Comment by hanliuxin5** [comment]
你把你要跳转到的页面的代码贴一下，报错信息说你的某个颜色给得不对导致无法解析

**Comment by aa453509345** [comment]
你的androidSDK是哪个版本的  早期版本不支持简写色值和RGB你可以在js代码中适配一下，或更新新版SDK
